import { StyleSheet } from "react-native";

export const conectaStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  content: {
    padding: 16,
    paddingBottom: 28,
    gap: 14,
  },
  heroCard: {
    width: "100%",
    borderRadius: 18,
    padding: 16,
    gap: 10,
    marginTop: 6,
    minHeight: 170,
    shadowColor: "#1e3a8a",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  heroBadge: {
    backgroundColor: "rgba(255,255,255,0.14)",
    color: "white",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    fontFamily: "barlow-semibold",
    fontSize: 12,
    letterSpacing: 0.4,
  },
  heroCity: {
    color: "rgba(255,255,255,0.92)",
    fontFamily: "barlow-medium",
    fontSize: 13,
  },
  heroTitle: {
    color: "white",
    fontFamily: "barlow-semibold",
    fontSize: 24,
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontFamily: "barlow-regular",
    fontSize: 14,
    lineHeight: 20,
  },
  heroTags: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 4,
  },
  heroTag: {
    color: "white",
    fontFamily: "barlow-medium",
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  sectionCard: {
    backgroundColor: "white",
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#cbd5e1",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontFamily: "barlow-semibold",
    fontSize: 18,
    color: "#0f172a",
  },
  sectionPill: {
    backgroundColor: "#e2e8f0",
    color: "#0f172a",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontFamily: "barlow-medium",
    fontSize: 12,
  },
  sectionPillAlt: {
    backgroundColor: "#ffedd5",
    color: "#ea580c",
  },
  sectionPillOrange: {
    backgroundColor: "#ffedd5",
    color: "#f97316",
  },
  sectionDescription: {
    fontSize: 14,
    fontFamily: "barlow-regular",
    color: "#475569",
    lineHeight: 20,
  },
  centerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    fontSize: 14,
    fontFamily: "barlow-regular",
    color: "#64748b",
  },
  hintText: {
    fontSize: 13,
    fontFamily: "barlow-regular",
    color: "#94a3b8",
  },
  errorText: {
    fontSize: 14,
    fontFamily: "barlow-regular",
    color: "#ef4444",
  },
  surveyCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  surveyTitle: {
    fontSize: 16,
    fontFamily: "barlow-medium",
    color: "#0f172a",
  },
  surveyQuestion: {
    fontSize: 14,
    fontFamily: "barlow-regular",
    color: "#475569",
  },
  optionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  optionButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    flexDirection: "row",
    alignItems: "center",
  },
  optionButtonSelected: {
    backgroundColor: "#0ea5e9",
    borderColor: "#0ea5e9",
  },
  optionText: {
    fontSize: 14,
    fontFamily: "barlow-medium",
    color: "#0f172a",
    lineHeight: 20,
  },
  optionCheck: {
    marginRight: 8,
  },
  optionTextSelected: {
    color: "white",
  },
  answerSaved: {
    fontSize: 13,
    fontFamily: "barlow-regular",
    color: "#16a34a",
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipSelected: {
    backgroundColor: "#0ea5e9",
    borderColor: "#0ea5e9",
  },
  chipDisabled: {
    opacity: 0.7,
  },
  chipText: {
    fontSize: 14,
    fontFamily: "barlow-medium",
    color: "#0f172a",
  },
  chipTextSelected: {
    color: "white",
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: "barlow-medium",
    color: "#0f172a",
    marginTop: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontFamily: "barlow-regular",
    color: "#0f172a",
    marginTop: 6,
    backgroundColor: "#f8fafc",
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
  },
  primaryButton: {
    backgroundColor: "#0ea5e9",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  primaryButtonText: {
    color: "white",
    fontFamily: "barlow-medium",
    fontSize: 15,
  },
  coordsBadge: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  coordsText: {
    fontSize: 13,
    fontFamily: "barlow-regular",
    color: "#0f172a",
  },
  photoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#0ea5e9",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    flex: 1,
    alignItems: "center",
  },
  secondaryButtonText: {
    fontFamily: "barlow-medium",
    color: "#0ea5e9",
    fontSize: 15,
  },
  photoPreview: {
    width: 64,
    height: 64,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  submitButton: {
    marginTop: 14,
    backgroundColor: "#0A2240",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
  },
  submitButtonText: {
    color: "white",
    fontFamily: "barlow-medium",
    fontSize: 16,
  },
  cancelButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#fff",
  },
  cancelButtonText: {
    color: "#0f172a",
    fontFamily: "barlow-medium",
    fontSize: 15,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
});
