import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const metodologyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 14,
  },
  sectionsStack: {
    gap: 14,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 14,
    padding: 4,
    marginHorizontal: 2,
    gap: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "transparent",
  },
  tabButtonText: {
    fontFamily: "barlow-light",
    color: "#00000066",
    fontSize: 14,
  },
  tabButtonTextActive: {
    fontFamily: "barlow-extrabold",
    color: Colors.NAVY_BLUE,
  },
  heroCard: {
    borderRadius: 0,
    padding: 18,
    gap: 10,
    shadowColor: "#1e3a8a",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  heroTitle: {
    color: "rgba(255,255,255,0.85)",
    fontFamily: "barlow-regular",
    fontSize: 16,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  heroTitlePill: {
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  heroName: {
    color: "#ffffff",
    fontFamily: "barlow-extrabold",
    fontSize: 26,
    letterSpacing: 0.6,
    textAlign: "center",
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontFamily: "barlow-regular",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  sponsorBox: {
    marginTop: 10,
    marginBottom: 4,
    alignSelf: "stretch",
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    alignItems: "center",
  },
  sponsorLogo: {
    width: 200,
    height: 90,
  },
  pointsRingWrapper: {
    marginTop: 10,
    alignItems: "center",
    gap: 8,
  },
  ringHint: {
    color: "rgba(255,255,255,0.7)",
    fontFamily: "barlow-medium",
    fontSize: 12,
    textAlign: "center",
  },
  heroStatsRow: {
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  statLabel: {
    color: "rgba(255,255,255,0.85)",
    fontFamily: "barlow-medium",
    fontSize: 12,
  },
  statValue: {
    color: "white",
    fontFamily: "barlow-semibold",
    fontSize: 20,
  },
  statHint: {
    color: "rgba(255,255,255,0.75)",
    fontFamily: "barlow-regular",
    fontSize: 12,
  },
  progressBar: {
    width: "100%",
    height: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#facc15",
  },
  progressLabel: {
    marginTop: 4,
    color: "rgba(255,255,255,0.9)",
    fontFamily: "barlow-medium",
    fontSize: 12,
  },
  sectionCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "barlow-semibold",
    color: Colors.NAVY_BLUE,
  },
  sectionSubtitle: {
    fontSize: 14,
    fontFamily: "barlow-regular",
    color: "#475569",
    lineHeight: 20,
  },
  streakPillRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(15,23,42,0.06)",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  streakPillLabel: {
    fontFamily: "barlow-semibold",
    fontSize: 14,
    color: "#0f172a",
  },
  streakPillValue: {
    fontFamily: "barlow-semibold",
    fontSize: 14,
    color: "#0f172a",
  },
  sectionPill: {
    backgroundColor: "#e0f2fe",
    color: "#0ea5e9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontFamily: "barlow-medium",
    fontSize: 12,
  },
  catalogPillButton: {
    shadowColor: "#f97316",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderRadius: 14,
  },
  catalogPill: {
    backgroundColor: "#f97316",
    color: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    fontFamily: "barlow-semibold",
    fontSize: 12,
    letterSpacing: 0.3,
  },
  pillMuted: {
    backgroundColor: "#e2e8f0",
    color: "#0f172a",
  },
  actionCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: "#f8fafc",
  },
  actionCardDisabled: {
    opacity: 0.7,
  },
  referralRow: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#f8fafc",
    gap: 10,
  },
  referralCodeBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  referralCodeLabel: {
    color: "#6b7280",
    fontFamily: "barlow-medium",
  },
  referralCodeValue: {
    fontSize: 18,
    fontFamily: "barlow-semibold",
    color: Colors.PRIMARY,
    letterSpacing: 1,
  },
  referralActiveBadge: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "rgba(34,197,94,0.14)",
    borderRadius: 10,
  },
  referralActiveText: {
    color: "#15803d",
    fontFamily: "barlow-semibold",
    fontSize: 12,
  },
  generateButton: {
    alignSelf: "flex-end",
    backgroundColor: Colors.PRIMARY,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  generateButtonText: {
    color: "#fff",
    fontFamily: "barlow-semibold",
    fontSize: 13,
  },
  referralButtons: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  shareButton: {
    backgroundColor: "#0f172a",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  shareButtonText: {
    color: "#fff",
    fontFamily: "barlow-semibold",
    fontSize: 13,
  },
  redeemContainer: {
    marginTop: 16,
    gap: 6,
  },
  redeemRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  redeemInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    fontFamily: "barlow-semibold",
    letterSpacing: 1,
  },
  redeemButton: {
    backgroundColor: Colors.PRIMARY,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
  },
  redeemButtonText: {
    color: "#fff",
    fontFamily: "barlow-semibold",
  },
  actionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  actionTextCol: {
    flex: 1,
  },
  actionTitle: {
    fontSize: 15,
    fontFamily: "barlow-semibold",
    color: "#0f172a",
  },
  actionSubtitle: {
    fontSize: 13,
    fontFamily: "barlow-regular",
    color: "#475569",
  },
  actionPoints: {
    fontSize: 15,
    fontFamily: "barlow-semibold",
    color: "#0ea5e9",
  },
  actionFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  actionFrequency: {
    fontSize: 12,
    fontFamily: "barlow-medium",
    color: "#0f172a",
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontFamily: "barlow-semibold",
    fontSize: 12,
    alignSelf: "flex-start",
  },
  badgeAvailable: {
    backgroundColor: "rgba(34,197,94,0.15)",
    color: "#15803d",
  },
  badgeBlocked: {
    backgroundColor: "rgba(248,113,113,0.15)",
    color: "#b91c1c",
  },
  historyRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  historyTitle: {
    fontSize: 14,
    fontFamily: "barlow-medium",
    color: "#0f172a",
  },
  historyDate: {
    fontSize: 12,
    fontFamily: "barlow-regular",
    color: "#64748b",
  },
  historyPoints: {
    fontSize: 14,
    fontFamily: "barlow-semibold",
  },
  historyThumb: {
    width: 42,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  pointsPositive: {
    color: "#16a34a",
  },
  pointsNegative: {
    color: "#ef4444",
  },
  mutedText: {
    color: "#64748b",
    fontFamily: "barlow-regular",
    fontSize: 13,
  },
  catalogContainer: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  catalogHeaderRow: {
    gap: 4,
  },
  catalogLoading: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    gap: 6,
  },
  catalogList: {
    gap: 10,
  },
  catalogCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 6,
  },
  catalogCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  catalogCardTitle: {
    fontFamily: "barlow-semibold",
    fontSize: 15,
    color: "#0f172a",
  },
  catalogCardSubtitle: {
    fontFamily: "barlow-regular",
    fontSize: 12,
    color: "#475569",
  },
  catalogPointsPill: {
    backgroundColor: "#0f172a",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  catalogPointsText: {
    color: "#fff",
    fontFamily: "barlow-semibold",
    fontSize: 12,
  },
  catalogDescription: {
    fontFamily: "barlow-regular",
    fontSize: 12,
    color: "#334155",
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  modalCard: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    padding: 16,
    paddingBottom: 20,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    gap: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
    maxHeight: "70%",
  },
  modalHeader: {
    gap: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "barlow-semibold",
    color: "#0f172a",
  },
  modalSubtitle: {
    fontSize: 13,
    fontFamily: "barlow-regular",
    color: "#475569",
  },
  modalCloseBtn: {
    alignSelf: "flex-end",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#0f172a",
  },
  modalCloseText: {
    color: "#fff",
    fontFamily: "barlow-semibold",
    fontSize: 13,
  },
  socialItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#f8fafc",
    marginBottom: 10,
    gap: 10,
  },
  socialTextCol: {
    flex: 1,
    gap: 4,
  },
  socialStatusCol: {
    alignItems: "flex-end",
    gap: 4,
  },
  socialSubtitle: {
    fontSize: 12,
    fontFamily: "barlow-medium",
    color: "#0f172a",
  },
  socialLinkLabel: {
    fontSize: 11,
    fontFamily: "barlow-regular",
    color: "#475569",
    maxWidth: 200,
  },
  processingText: {
    fontSize: 11,
    fontFamily: "barlow-medium",
    color: "#0ea5e9",
  },
});
