/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInForm` | `/SignInForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/fields` | `/fields`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/metodology` | `/metodology`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignInForm` | `/SignInForm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(call)'}/fields` | `/fields`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(call)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(call)'}/metodology` | `/metodology`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(call)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignInForm${`?${string}` | `#${string}` | ''}` | `/SignInForm${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(call)'}/fields${`?${string}` | `#${string}` | ''}` | `/fields${`?${string}` | `#${string}` | ''}` | `${'/(call)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(call)'}/metodology${`?${string}` | `#${string}` | ''}` | `/metodology${`?${string}` | `#${string}` | ''}` | `${'/(call)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/screens/CalendarScreen${`?${string}` | `#${string}` | ''}` | `/screens/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/screens/SettingsScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInForm` | `/SignInForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/fields` | `/fields`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/metodology` | `/metodology`; params?: Router.UnknownInputParams; } | { pathname: `${'/(call)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
